### ISSUE TITLE
IPv6

### ISSUE THREAD

**Issue by glaxx** [openlab-aux/labnetz-doku#5]
As vrs said on the last Nerdnight, IPv6 support would be appreciated.

**Comment by sternenseemann** [comment]
Isn't this a problemerino wis da Kabel Deutscheland internet service provider?

**Comment by verbosemode** [comment]
If something doesn't work in networking, you are just not using enough tunnels yet ;-)

Due to the wonderful "Störerhaftung" in Germany, we shouldn't use any IPv6 prefixes from our upstream ISP. Maybe we can get IPv6 from our current v4 tunnel provider, either through normal routing or via DHCPv6 prefix delegation. Another option would be to have a second tunnel to he.net for example. But I don't have any experience regarding their privacy policy. I'm asking a friend of another hackerspace right now to figure out how their v6 setup looks like.

**Comment by sternenseemann** [comment]
Tunneling sounds like the way to go.

**Comment by pRiVi** [comment]
Should be fixed together with #4

**Comment by sternenseemann** [comment]
bump

**Comment by pRiVi** [comment]
Fixed.
